package LOREntites;
// Generated Apr 7, 2018 9:35:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jeu generated by hbm2java
 */
public class Jeu  implements java.io.Serializable {


     private Integer idJeu;
     private Editeur editeur;
     private String nom;
     private String description;
     private Set versionJeus = new HashSet(0);
     private Set tags = new HashSet(0);

    public Jeu() {
    }

	
    public Jeu(Editeur editeur) {
        this.editeur = editeur;
    }
    public Jeu(Editeur editeur, String nom, String description, Set versionJeus, Set tags) {
       this.editeur = editeur;
       this.nom = nom;
       this.description = description;
       this.versionJeus = versionJeus;
       this.tags = tags;
    }
   
    public Integer getIdJeu() {
        return this.idJeu;
    }
    
    public void setIdJeu(Integer idJeu) {
        this.idJeu = idJeu;
    }
    public Editeur getEditeur() {
        return this.editeur;
    }
    
    public void setEditeur(Editeur editeur) {
        this.editeur = editeur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getVersionJeus() {
        return this.versionJeus;
    }
    
    public void setVersionJeus(Set versionJeus) {
        this.versionJeus = versionJeus;
    }
    public Set getTags() {
        return this.tags;
    }
    
    public void setTags(Set tags) {
        this.tags = tags;
    }




}


