package LOREntites;
// Generated Apr 6, 2018 5:26:24 PM by Hibernate Tools 4.3.1



/**
 * Version generated by hbm2java
 */
public class Version  implements java.io.Serializable {


     private Integer idVersion;
     private Jeu jeu;
     private String codeBarre;
     private String nom;
     private Float prix;
     private int stock;

    public Version() {
    }

	
    public Version(Jeu jeu, String codeBarre, int stock) {
        this.jeu = jeu;
        this.codeBarre = codeBarre;
        this.stock = stock;
    }
    public Version(Jeu jeu, String codeBarre, String nom, Float prix, int stock) {
       this.jeu = jeu;
       this.codeBarre = codeBarre;
       this.nom = nom;
       this.prix = prix;
       this.stock = stock;
    }
   
    public Integer getIdVersion() {
        return this.idVersion;
    }
    
    public void setIdVersion(Integer idVersion) {
        this.idVersion = idVersion;
    }
    public Jeu getJeu() {
        return this.jeu;
    }
    
    public void setJeu(Jeu jeu) {
        this.jeu = jeu;
    }
    public String getCodeBarre() {
        return this.codeBarre;
    }
    
    public void setCodeBarre(String codeBarre) {
        this.codeBarre = codeBarre;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Float getPrix() {
        return this.prix;
    }
    
    public void setPrix(Float prix) {
        this.prix = prix;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }




}


