package LOREntities;
// Generated May 6, 2018 10:51:49 PM by Hibernate Tools 4.3.1



/**
 * DecrireId generated by hbm2java
 */
public class DecrireId  implements java.io.Serializable {


     private int idTagFk;
     private int idJeuFk;

    public DecrireId() {
    }

    public DecrireId(int idTagFk, int idJeuFk) {
       this.idTagFk = idTagFk;
       this.idJeuFk = idJeuFk;
    }
   
    public int getIdTagFk() {
        return this.idTagFk;
    }
    
    public void setIdTagFk(int idTagFk) {
        this.idTagFk = idTagFk;
    }
    public int getIdJeuFk() {
        return this.idJeuFk;
    }
    
    public void setIdJeuFk(int idJeuFk) {
        this.idJeuFk = idJeuFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DecrireId) ) return false;
		 DecrireId castOther = ( DecrireId ) other; 
         
		 return (this.getIdTagFk()==castOther.getIdTagFk())
 && (this.getIdJeuFk()==castOther.getIdJeuFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTagFk();
         result = 37 * result + this.getIdJeuFk();
         return result;
   }   


}


