package LOREntities;
// Generated May 4, 2018 10:53:06 PM by Hibernate Tools 4.3.1



/**
 * Decrire generated by hbm2java
 */
public class Decrire  implements java.io.Serializable {


     private DecrireId id;

    public Decrire() {
    }

    public Decrire(DecrireId id) {
       this.id = id;
    }
   
    public DecrireId getId() {
        return this.id;
    }
    
    public void setId(DecrireId id) {
        this.id = id;
    }




}


