package LOREntities;
// Generated Jun 7, 2018 5:40:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fabricant generated by hbm2java
 */
public class Fabricant  implements java.io.Serializable {


     private Integer idFabricant;
     private String nomFabricant;
     private Set consoles = new HashSet(0);

    public Fabricant() {
    }

	
    public Fabricant(String nomFabricant) {
        this.nomFabricant = nomFabricant;
    }
    public Fabricant(String nomFabricant, Set consoles) {
       this.nomFabricant = nomFabricant;
       this.consoles = consoles;
    }
   
    public Integer getIdFabricant() {
        return this.idFabricant;
    }
    
    public void setIdFabricant(Integer idFabricant) {
        this.idFabricant = idFabricant;
    }
    public String getNomFabricant() {
        return this.nomFabricant;
    }
    
    public void setNomFabricant(String nomFabricant) {
        this.nomFabricant = nomFabricant;
    }
    public Set getConsoles() {
        return this.consoles;
    }
    
    public void setConsoles(Set consoles) {
        this.consoles = consoles;
    }




}


