package LOREntities;
// Generated Jun 15, 2018 7:35:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne  implements java.io.Serializable {


     private Integer idPersonne;
     private Ville ville;
     private String nom;
     private String prenom;
     private String adresse;
     private Date deDeNaissance;
     private String mail;
     private String telephone;
     private String societe;
     private Set factures = new HashSet(0);

    public Personne() {
    }

	
    public Personne(Ville ville, String nom, String prenom, String adresse, Date deDeNaissance, String mail, String telephone) {
        this.ville = ville;
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.deDeNaissance = deDeNaissance;
        this.mail = mail;
        this.telephone = telephone;
    }
    public Personne(Ville ville, String nom, String prenom, String adresse, Date deDeNaissance, String mail, String telephone, String societe, Set factures) {
       this.ville = ville;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.deDeNaissance = deDeNaissance;
       this.mail = mail;
       this.telephone = telephone;
       this.societe = societe;
       this.factures = factures;
    }
   
    public Integer getIdPersonne() {
        return this.idPersonne;
    }
    
    public void setIdPersonne(Integer idPersonne) {
        this.idPersonne = idPersonne;
    }
    public Ville getVille() {
        return this.ville;
    }
    
    public void setVille(Ville ville) {
        this.ville = ville;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public Date getDeDeNaissance() {
        return this.deDeNaissance;
    }
    
    public void setDeDeNaissance(Date deDeNaissance) {
        this.deDeNaissance = deDeNaissance;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getSociete() {
        return this.societe;
    }
    
    public void setSociete(String societe) {
        this.societe = societe;
    }
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }




}


