package LOREntities;
// Generated Jun 15, 2018 7:35:49 PM by Hibernate Tools 4.3.1



/**
 * PromoJeu generated by hbm2java
 */
public class PromoJeu  implements java.io.Serializable {


     private Integer idPromoJeu;
     private VersionJeu versionJeu;
     private float coteJeu;
     private float prixPromoJeu;

    public PromoJeu() {
    }

    public PromoJeu(VersionJeu versionJeu, float coteJeu, float prixPromoJeu) {
       this.versionJeu = versionJeu;
       this.coteJeu = coteJeu;
       this.prixPromoJeu = prixPromoJeu;
    }
   
    public Integer getIdPromoJeu() {
        return this.idPromoJeu;
    }
    
    public void setIdPromoJeu(Integer idPromoJeu) {
        this.idPromoJeu = idPromoJeu;
    }
    public VersionJeu getVersionJeu() {
        return this.versionJeu;
    }
    
    public void setVersionJeu(VersionJeu versionJeu) {
        this.versionJeu = versionJeu;
    }
    public float getCoteJeu() {
        return this.coteJeu;
    }
    
    public void setCoteJeu(float coteJeu) {
        this.coteJeu = coteJeu;
    }
    public float getPrixPromoJeu() {
        return this.prixPromoJeu;
    }
    
    public void setPrixPromoJeu(float prixPromoJeu) {
        this.prixPromoJeu = prixPromoJeu;
    }




}


