package LOREntities;
// Generated May 2, 2018 8:07:14 PM by Hibernate Tools 4.3.1



/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer idTag;
     private String libelle;

    public Tag() {
    }

    public Tag(String libelle) {
       this.libelle = libelle;
    }
   
    public Integer getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


