package LOREntities;
// Generated May 10, 2018 11:22:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone  implements java.io.Serializable {


     private int idZone;
     private String nomZone;
     private Set versionConsoles = new HashSet(0);
     private Set versionJeus = new HashSet(0);

    public Zone() {
    }

	
    public Zone(int idZone, String nomZone) {
        this.idZone = idZone;
        this.nomZone = nomZone;
    }
    public Zone(int idZone, String nomZone, Set versionConsoles, Set versionJeus) {
       this.idZone = idZone;
       this.nomZone = nomZone;
       this.versionConsoles = versionConsoles;
       this.versionJeus = versionJeus;
    }
   
    public int getIdZone() {
        return this.idZone;
    }
    
    public void setIdZone(int idZone) {
        this.idZone = idZone;
    }
    public String getNomZone() {
        return this.nomZone;
    }
    
    public void setNomZone(String nomZone) {
        this.nomZone = nomZone;
    }
    public Set getVersionConsoles() {
        return this.versionConsoles;
    }
    
    public void setVersionConsoles(Set versionConsoles) {
        this.versionConsoles = versionConsoles;
    }
    public Set getVersionJeus() {
        return this.versionJeus;
    }
    
    public void setVersionJeus(Set versionJeus) {
        this.versionJeus = versionJeus;
    }




}


