/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import bean.Form;
import bean.ProduitForm;
import controleur.Rapport;
import java.util.Vector;
import javax.swing.JPanel;

/**
 *
 * @author bornbygoogle
 */
public class Resultat <F extends Form> extends javax.swing.JPanel
{
    protected Chercheur parent;
    protected Vector<F> res;
    protected static String [] typeProduit = {
        "Code Barre",
        "Nom",
        "Edition",
        "Zone",
        "Développeur"};

    /**
     * Creates new form Resultat
     */
    public Resultat(Chercheur parent)
    {
        this.parent = parent;
        initComponents();
        
        //destruction du tableau par défaut
        this.table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldErrorRecherche = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        fieldErrorRecherche.setForeground(new java.awt.Color(255, 3, 0));
        fieldErrorRecherche.setText("Aucun résultat ne correspond à votre recherche");

        table.setAutoCreateRowSorter(true);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code Barre", "Nom", "Quantité disponible", "Developpeur", "Date de sortie", "Plus Infos"
            }
        ));
        table.setShowVerticalLines(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addComponent(fieldErrorRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldErrorRecherche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void tableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tableKeyTyped
    
    //important : il est nécessaire que le vecteur contienne des données de type HOMOGENE (autrement dit, pas des formulaires différents
    public void afficherRes(Vector<F> res)
    {
        this.res = res;
        
        //Affichage du nombre de résultats
        if (res.size() == 0)
            afficherErreur("Aucun résultat.");
        else if (res.size() > 1)
        {
            this.fieldErrorRecherche.setText(res.size() + "résultats.");
            
            //On recrée le tableau
            Form test = res.iterator().next(); //on commence par déterminer le type de données avec un test. TODO: plus propre ?
            if (test instanceof ProduitForm)
            {
                Object[][] donnees = new Object[res.size()][];
                int rowIndex = 0;
                for (Form f : res)
                {
                    ProduitForm pf = (ProduitForm) f;
                    Object[] donneesLigne = {
                        pf.getCodeBarre(),
                        pf.getNom(),
                        pf.getEdition(),
                        pf.getZone(),
                        pf.getEditeur()
                    };
                    donnees[rowIndex] = donneesLigne;
                    rowIndex++;
                }
                this.table.setModel(
                        new javax.swing.table.DefaultTableModel(donnees,typeProduit));
            }
        }
        else //if (res.size() == 1)
        {
            this.fieldErrorRecherche.setText("1 résultat.");
            //TODO : sélectionner directement le résultat.
        }
    }
    public void afficherErreur(String error)
    {
        //TODO changer la couleur
        this.fieldErrorRecherche.setText(error);
        this.res = null;
        //TODO effacer le tableau
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel fieldErrorRecherche;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
